# -------------------------------- dev-环境 -----------------------------------
# 设置当前模块服务名称
spring:
  application:
    name: document-server

# 设置启动端口号
server:
  port: 48082
  servlet:
    context-path: /api/document


# 设置日志文件名称、日志配置文件路径
logging:
  config: classpath:logback-dev.xml

logback:
  file:
    path: ${user.home}/FilesBottleDev_Logs/${spring.application.name}
