# -------------------------------- dev-环境 -----------------------------------
# 设置当前模块服务名称
spring:
  application:
    name: ffmpeg-server

# 设置启动端口号
server:
  port: 48086


# 在生产环境中进行部署的时候需要进行指定、运行 jar 包 (nginx ip + 端口号)
nginx:
  address: 140.246.171.8:5000


ffmpeg:
  neturl: http://${nginx.address}/hlsvideo/
  path: /usr/bin/ffmpeg
  filepath: /home/travis/hlsvideo/



--- # 修改上传文件大小的限制
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

# 设置日志文件名称、日志配置文件路径
logging:
  config: classpath:logback-pro.xml

logback:
  file:
    path: ${user.home}/FilesBottleDev_Logs/${spring.application.name}
