spring:
  cloud:
    gateway:
      routes:
        - id: document-server
          uri: lb://document-server
          predicates:
            - Path=/api/document/**
        - id: auth
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
        - id: knife4j
          uri: lb://knife4j-server
          predicates:
            - Path=/knife4j/**
